name: dr_health
description: A Medication Reminder and Health Care Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  flutter_local_notifications: ^8.1.1+1 # show local notification
  flutter_native_timezone: ^2.0.0 # show sheduled notification
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  video_player: ^2.1.13
  flutter_search_bar: ^2.1.0
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3 #^2.4.0
  http: ^0.13.3
  get: ^4.3.8
  system_settings: ^2.0.0
  package_info_plus: ^1.0.6
  flutter_slidable: ^0.6.0
  auto_size_text: ^3.0.0-nullsafety.0 #^2.1.0
  animated_text_kit: ^4.2.1 #^2.5.3
  animated_widgets: ^1.1.0 #^1.0.6
  flutter_sms: ^2.3.1
  flutter_native_splash: ^1.2.1
  path: ^1.8.0
  rxdart: ^0.27.2 # listen for notification
  internet_connection_checker: ^0.0.1+2
  font_awesome_flutter: ^9.1.0
  curved_navigation_bar: ^1.0.1
  flutter_speed_dial: ^4.4.0+1
  shared_preferences: ^2.0.6
  # flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/popins_regular.ttf
        - asset: assets/fonts/popins_light.ttf
          weight: 300
        - asset: assets/fonts/popins_bold.ttf
          weight: 700
        - asset: assets/fonts/popins_semibold.ttf
          weight: 600
        - asset: assets/fonts/popins_medium.ttf
          weight: 500